bookdb_re_exam/config/routes.rb
Rails.application.routes.draw do
  resources :readers
  resources :books

  root 'books#index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

bookdb_re_exam/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

bookdb_re_exam/app/models/book.rb
class Book < ApplicationRecord
    validates :bookname, presence: true
    validates :author, presence: true

    has_many :readers
  end
  

bookdb_re_exam/app/models/reader.rb
class Reader < ApplicationRecord
  belongs_to :book
  validates :readername, presence: true
  validates :comments, length: { maximum: 20 }
  validates :rating, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 5 }
end

bookdb_re_exam/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookdb_re_exam/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:bookname, :author)
    end
end

bookdb_re_exam/app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  before_action :set_reader, only: %i[ show edit update destroy ]

  # GET /readers or /readers.json
  def index
    @readers = Reader.all
  end

  # GET /readers/1 or /readers/1.json
  def show
  end

  # GET /readers/new
  def new
    @reader = Reader.new
  end

  # GET /readers/1/edit
  def edit
  end

  # POST /readers or /readers.json
  def create
    @reader = Reader.new(reader_params)

    respond_to do |format|
      if @reader.save
        format.html { redirect_to reader_url(@reader), notice: "Reader was successfully created." }
        format.json { render :show, status: :created, location: @reader }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /readers/1 or /readers/1.json
  def update
    respond_to do |format|
      if @reader.update(reader_params)
        format.html { redirect_to reader_url(@reader), notice: "Reader was successfully updated." }
        format.json { render :show, status: :ok, location: @reader }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readers/1 or /readers/1.json
  def destroy
    @reader.destroy

    respond_to do |format|
      format.html { redirect_to readers_url, notice: "Reader was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reader
      @reader = Reader.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reader_params
      params.require(:reader).permit(:readername, :comments, :book_id, :rating)
    end
    
end

bookdb_re_exam/app/helpers/application_helper.rb
module ApplicationHelper
end

bookdb_re_exam/app/helpers/books_helper.rb
module BooksHelper
end

bookdb_re_exam/app/helpers/readers_helper.rb
module ReadersHelper
end

bookdb_re_exam/app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Bookname:</strong>
    <%= book.bookname %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>

</div>

bookdb_re_exam/app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :bookname, style: "display: block" %>
    <%= form.text_field :bookname %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

bookdb_re_exam/app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

bookdb_re_exam/app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Show this book", book %>
    </p>
  <% end %>
</div>

<%= link_to "New book", new_book_path %>

bookdb_re_exam/app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

bookdb_re_exam/app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<h4>Readers:</h4>
<ul>
  <% @book.readers.each do |reader| %>
    <li>
      <strong>Name:</strong> <%= reader.readername %><br>
      <strong>Comments:</strong> <%= reader.comments %>
    </li>
  <% end %>
</ul>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

bookdb_re_exam/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookdb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

bookdb_re_exam/app/views/readers/_form.html.erb
<%= form_with(model: reader) do |form| %>
  <% if reader.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reader.errors.count, "error") %> prohibited this reader from being saved:</h2>

      <ul>
        <% reader.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :readername, style: "display: block" %>
    <%= form.text_field :readername %>
  </div>

  <!-- app/views/readers/_form.html.erb -->
  <div>
    <%= form.label :rating, style: "display: block" %> 
    <%= form.number_field :rating, min: 1, max: 5 %>
  </div>


  <div>
    <%= form.label :comments, style: "display: block" %>
    <%= form.text_area :comments %>
  </div>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.text_field :book_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

bookdb_re_exam/app/views/readers/_reader.html.erb
<div id="<%= dom_id reader %>">
  <p>
    <strong>Readername:</strong>
    <%= reader.readername %>
  </p>

  <p>
    <strong>Comments:</strong>
    <%= reader.comments %>
  </p>

  <p>
    <strong>Book:</strong>
    <%= reader.book_id %>
  </p>

</div>

bookdb_re_exam/app/views/readers/edit.html.erb
<h1>Editing reader</h1>

<%= render "form", reader: @reader %>

<br>

<div>
  <%= link_to "Show this reader", @reader %> |
  <%= link_to "Back to readers", readers_path %>
</div>

bookdb_re_exam/app/views/readers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Readers</h1>

<div id="readers">
  <% @readers.each do |reader| %>
    <%= render reader %>
    <p>
      <%= link_to "Show this reader", reader %>
    </p>
  <% end %>
</div>

<%= link_to "New reader", new_reader_path %>

bookdb_re_exam/app/views/readers/new.html.erb
<h1>New reader</h1>

<%= render "form", reader: @reader %>

<br>

<div>
  <%= link_to "Back to readers", readers_path %>
</div>

bookdb_re_exam/app/views/readers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reader %>

<p>
  <strong>Rating:</strong>
  <%= @reader.rating %>
</p>

<div>
  <%= link_to "Edit this reader", edit_reader_path(@reader) %> |
  <%= link_to "Back to readers", readers_path %>

  <%= button_to "Destroy this reader", @reader, method: :delete %>
</div>